### ISSUE TITLE
[catkin_prepare_release] UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1592: ordinal not in range(128)

### ISSUE THREAD

**Issue by 130s** [ros/catkin#901]
```
$ git clone git@github.com:ros-planning/geometric_shapes.git && cd geometric_shapes/
$ catkin_prepare_release 
Prepare the source repository for a release.
Repository type: git
Found packages: geometric_shapes
Prepare release of version '0.5.3' [Y/n]?
Trying to push to remote repository (dry run)...
Everything up-to-date
Checking if working copy is clean (no staged changes, no modified files, no untracked files)...
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_prepare_release", line 390, in <module>
    main()
  File "/opt/ros/kinetic/bin/catkin_prepare_release", line 319, in main
    update_changelog_sections(missing_changelogs_but_forthcoming, new_version)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/package_version.py", line 131, in update_changelog_sections
    f.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1592: ordinal not in range(128)
$ git log -n 1
commit 70262c6303f8e1ae348b92db1aca588c61890b6e
$ which  catkin_prepare_release
/opt/ros/kinetic/bin/catkin_prepare_release
$ apt-cache policy ros-kinetic-catkin
ros-kinetic-catkin:
  Installed: 0.7.6-0xenial-20170217-212821-0800
  Candidate: 0.7.6-0xenial-20170217-212821-0800
```

`xf6` in unicode seems to be [o + umlaut](http://www.utf8-chartable.de/unicode-utf8-table.pl?names=-&unicodeinhtml=hex), which occurs in [CHANGELOG.rst](https://github.com/ros-planning/geometric_shapes/blob/70262c6303f8e1ae348b92db1aca588c61890b6e/CHANGELOG.rst).

**Comment by bmagyar** [comment]
I second that.

Just encounterd this today with `u"\xfc"` corresponding to `ü`.

**Comment by mikaelarguedas** [comment]
I faced this issue too and the patch in #902 fixed it, allowing me to release

**Comment by dirk-thomas** [comment]
Addressed by #902.

**Comment by fmessmer** [comment]
I'm still getting this error...for me #902 only fixed the exception during the `catkin_generate_changelog`-step
